export { default as DashboardPage } from "./DashboardPage"
export { default as EducationPage } from "./education/EducationPage"
export { default as WorkPage } from './work/WorkPage'
export { default as ProjectsPage } from "./projects/ProjectsPage"
export { default as SkillPage } from "./skills/SkillPage"
export { default as HobbiesPage } from "./hobbies/HobbiesPage"
export { default as TestimonialsPage } from './testimonials/TestimonialsPage'
export { default as ResumePage } from "./resume/ResumePage"
export { default as ContactPage } from "./contact/ContactPage"