export type { Testimonial, TestimonialRequestModel } from './model/testimonial'
export { TestimonialStatus } from './model/testimonial'
export { addTestimonial } from './api/addTestimonial'
export { getAllTestimonials } from './api/getAllTestimonials'
export { getAllTestimonialApprovedTestimonials } from './api/getAllApprovedTestimonials'
export { updateTestimonialStatus } from './api/updateTestimonialStatus'
export { deleteTestimonial } from './api/deleteTestimonial'